export const NUM_CHARS_OWNER_CODE = 6;
export const NUM_CHARS_JOIN_CODE = 6;
export const NUM_CHARS_SUPERPOWER_BOX_CODE = 8;

export const MAX_NUM_CHARS_SUPERPOWER_DESCRIPTION = 25;
export const MAX_NUM_CHARS_SUPERHERO_NAME = 20;
