export const getAutoGenComment = (sourceFilePath?: string): string => {
  return [
    "/*",
    "  DO NOT MANUALLY MODIFY THIS CODE.",
    `  THIS CODE WAS AUTOGENERATED${
      sourceFilePath != null ? ` FROM ${sourceFilePath}` : ""
    }.`,
    "  RUN `yarn codegen` AT PROJECT ROOT TO REGENERATE THIS FILE.",
    "*/\n",
  ].join("\n");
};

export const getPartialGenTopComment = (sourceFilePath?: string): string => {
  return [
    "/*",
    "  DO NOT MANUALLY MODIFY THE TOP SECTION OF THIS CODE.",
    `  THIS CODE WAS PARTIALLY GENERATED${
      sourceFilePath != null ? ` FROM ${sourceFilePath}` : ""
    }.`,
    "  MAKE YOUR CHANGES AT THE BOTTOM, BELOW THE MANUAL CHANGES COMMENT.",
    "  RUN `yarn codegen` AT PROJECT ROOT TO REGENERATE THIS FILE.",
    "*/\n",
  ].join("\n");
};

export const getPartialGenBottomComment = (): string => {
  return "// MAKE YOUR MANUAL CHANGES BELOW";
};
